"""Initial migration

Revision ID: 47a25e91f557
Revises: 
Create Date: 2026-07-16 15:48:15.331912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a25e91f557'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_area_desc'), ['desc'], unique=False)
        batch_op.create_index(batch_op.f('ix_area_name'), ['name'], unique=False)

    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_type'), ['type'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('pw_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pw_hash')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('completed_by', sa.Integer(), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_completed_by'), ['completed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_desc'), ['desc'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_submitted_by_id'), ['submitted_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_submitted_by_id'))
        batch_op.drop_index(batch_op.f('ix_issues_status'))
        batch_op.drop_index(batch_op.f('ix_issues_priority'))
        batch_op.drop_index(batch_op.f('ix_issues_desc'))
        batch_op.drop_index(batch_op.f('ix_issues_date'))
        batch_op.drop_index(batch_op.f('ix_issues_completed_by'))
        batch_op.drop_index(batch_op.f('ix_issues_area'))

    op.drop_table('issues')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_account_type'))

    op.drop_table('user')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_type'))
        batch_op.drop_index(batch_op.f('ix_company_phone'))
        batch_op.drop_index(batch_op.f('ix_company_name'))
        batch_op.drop_index(batch_op.f('ix_company_email'))

    op.drop_table('company')
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_area_name'))
        batch_op.drop_index(batch_op.f('ix_area_desc'))

    op.drop_table('area')
    # ### end Alembic commands ###
