"""remigration, added naming schema and relationship

Revision ID: a403d5fbc7a4
Revises: 47a25e91f557
Create Date: 2026-07-21 20:03:50.177106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a403d5fbc7a4'
down_revision = '47a25e91f557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_issues_area'))
        batch_op.create_index(batch_op.f('ix_issues_area_id'), ['area_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_issues_area_id_area'), 'area', ['area_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('area')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_pw_hash'), ['pw_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_pw_hash'), type_='unique')

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_issues_area_id_area'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_issues_area_id'))
        batch_op.create_index(batch_op.f('ix_issues_area'), ['area'], unique=False)
        batch_op.drop_column('area_id')

    # ### end Alembic commands ###
