"""added issues table, first migration using alembic

Revision ID: bc25f7d9678e
Revises: 
Create Date: 2026-06-30 14:08:09.845632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc25f7d9678e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=150), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('completed_by', sa.Integer(), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_completed_by'), ['completed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_desc'), ['desc'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_submitted_by'), ['submitted_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_submitted_by'))
        batch_op.drop_index(batch_op.f('ix_issues_status'))
        batch_op.drop_index(batch_op.f('ix_issues_priority'))
        batch_op.drop_index(batch_op.f('ix_issues_desc'))
        batch_op.drop_index(batch_op.f('ix_issues_date'))
        batch_op.drop_index(batch_op.f('ix_issues_completed_by'))
        batch_op.drop_index(batch_op.f('ix_issues_area'))

    op.drop_table('issues')
    # ### end Alembic commands ###
